# Generated by Django 4.2.4 on 2023-08-29 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('enabled', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('scrape_frequency', models.IntegerField(default=3600)),
                ('last_scrape_at', models.DateTimeField(null=True, verbose_name='last scrape at')),
            ],
        ),
        migrations.CreateModel(
            name='Giveaway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('GAME', 'Game'), ('DEMO', 'Demo'), ('DLC', 'DLC'), ('LOOT', 'Loot'), ('ALPHA', 'Alpha'), ('BETA', 'Beta'), ('MEMBERSHIP', 'Membership'), ('OTHER', 'Other')], default='OTHER', max_length=10)),
                ('title', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('url', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('QUEUED', 'Queued'), ('PUBLISHED', 'Published'), ('CANCELED', 'Canceled'), ('EXPIRED', 'Expired')], default='CREATED', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('post_id', models.TextField(blank=True)),
                ('post_title', models.TextField(blank=True)),
                ('post_url', models.TextField(blank=True)),
                ('post_image', models.TextField(blank=True)),
                ('platforms', models.ManyToManyField(blank=True, to='backend.platform')),
                ('supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.supplier')),
            ],
            options={
                'indexes': [models.Index(fields=['status'], name='backend_giv_status_38439a_idx')],
            },
        ),
    ]
