# Generated by Django 4.2.4 on 2023-08-14 13:12

from django.db import migrations


def forwards_func(apps, schema_editor):
    Platform = apps.get_model("backend", "Platform")
    db_alias = schema_editor.connection.alias
    Platform.objects.using(db_alias).bulk_create([
        Platform(id="steam", title="Steam"),
        Platform(id="gog", title="GOG"),
        Platform(id="epic_games", title="Epic Games"),
        Platform(id="ubisoft_connect", title="Ubisoft Connect"),
        Platform(id="battle_net", title="Battle.Net"),
        Platform(id="origin", title="Origin"),
        Platform(id="indiegala", title="Indiegala"),
        Platform(id="microsoft", title="Microsoft"),
        Platform(id="itch_io", title="itch.io"),
        Platform(id="rockstar_games", title="Rockstar Games"),
        Platform(id="oculus", title="Oculus"),
        Platform(id="pc", title="PC"),
        Platform(id="ps4", title="PS4"),
        Platform(id="ps5", title="PS5"),
        Platform(id="playstation", title="Playstation"),
        Platform(id="xbox_one", title="Xbox One"),
        Platform(id="xbox_360", title="Xbox 360"),
        Platform(id="xbox", title="Xbox"),
        Platform(id="switch", title="Switch"),
        Platform(id="nintendo", title="Nintendo"),
        Platform(id="amazon", title="Amazon"),
        Platform(id="ios", title="iOS"),
        Platform(id="android", title="Android"),
        Platform(id="mobile", title="Mobile"),
    ])


def reverse_func(apps, schema_editor):
    Platform = apps.get_model("backend", "Platform")
    db_alias = schema_editor.connection.alias
    Platform.objects.using(db_alias).filter(id="steam").delete(),
    Platform.objects.using(db_alias).filter(id="gog").delete(),
    Platform.objects.using(db_alias).filter(id="epic_games").delete(),
    Platform.objects.using(db_alias).filter(id="ubisoft_connect").delete(),
    Platform.objects.using(db_alias).filter(id="battle_net").delete(),
    Platform.objects.using(db_alias).filter(id="origin").delete(),
    Platform.objects.using(db_alias).filter(id="indiegala").delete(),
    Platform.objects.using(db_alias).filter(id="microsoft").delete(),
    Platform.objects.using(db_alias).filter(id="itch_io").delete(),
    Platform.objects.using(db_alias).filter(id="rockstar_games").delete(),
    Platform.objects.using(db_alias).filter(id="oculus").delete(),
    Platform.objects.using(db_alias).filter(id="pc").delete(),
    Platform.objects.using(db_alias).filter(id="ps4").delete(),
    Platform.objects.using(db_alias).filter(id="ps5").delete(),
    Platform.objects.using(db_alias).filter(id="playstation").delete(),
    Platform.objects.using(db_alias).filter(id="xbox_one").delete(),
    Platform.objects.using(db_alias).filter(id="xbox_360").delete(),
    Platform.objects.using(db_alias).filter(id="xbox").delete(),
    Platform.objects.using(db_alias).filter(id="switch").delete(),
    Platform.objects.using(db_alias).filter(id="nintendo").delete(),
    Platform.objects.using(db_alias).filter(id="amazon").delete(),
    Platform.objects.using(db_alias).filter(id="ios").delete(),
    Platform.objects.using(db_alias).filter(id="android").delete(),
    Platform.objects.using(db_alias).filter(id="mobile").delete(),


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
