# Generated by Django 4.2.4 on 2023-08-14 13:12

from django.db import migrations


def forwards_func(apps, schema_editor):
    Supplier = apps.get_model("backend", "Supplier")
    db_alias = schema_editor.connection.alias
    Supplier.objects.using(db_alias).bulk_create([
        Supplier(id="alienware", title="Alienware", scrape_frequency=600),
        Supplier(id="amazon", title="Amazon"),
        Supplier(id="epic_games", title="Epic Games"),
        Supplier(id="gog", title="GOG"),
        Supplier(id="humble_bundle", title="Humble Bundle"),
        Supplier(id="indiegala", title="IndieGala"),
        Supplier(id="intel", title="Intel"),
        Supplier(id="is_there_any_deal", title="IsThereAnyDeal"),
        Supplier(id="itch_io", title="itch.io"),
        Supplier(id="mmobomb", title="MMOBomb", scrape_frequency=600),
        Supplier(id="mmorpg", title="MMORPG", scrape_frequency=600),
        Supplier(id="playstation", title="Playstation"),
        Supplier(id="reddit", title="Reddit", scrape_frequency=7200, order=1),
        Supplier(id="steelseries", title="Steelseries", scrape_frequency=600),
        Supplier(id="nintendo", title="Nintendo Switch"),
    ])


def reverse_func(apps, schema_editor):
    Supplier = apps.get_model("backend", "Supplier")
    db_alias = schema_editor.connection.alias
    Supplier.objects.using(db_alias).filter(id="alienware").delete(),
    Supplier.objects.using(db_alias).filter(id="amazon").delete(),
    Supplier.objects.using(db_alias).filter(id="epic_games").delete(),
    Supplier.objects.using(db_alias).filter(id="gog").delete(),
    Supplier.objects.using(db_alias).filter(id="humble_bundle").delete(),
    Supplier.objects.using(db_alias).filter(id="indiegala").delete(),
    Supplier.objects.using(db_alias).filter(id="intel").delete(),
    Supplier.objects.using(db_alias).filter(id="itch_io").delete(),
    Supplier.objects.using(db_alias).filter(id="mmobomb").delete(),
    Supplier.objects.using(db_alias).filter(id="mmorpg").delete(),
    Supplier.objects.using(db_alias).filter(id="playstation").delete(),
    Supplier.objects.using(db_alias).filter(id="reddit").delete(),
    Supplier.objects.using(db_alias).filter(id="steelseries").delete(),
    Supplier.objects.using(db_alias).filter(id="nintendo").delete(),


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_platforms'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
