# Generated by Django 4.2.4 on 2023-09-13 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_suppliers'),
    ]

    operations = [
        migrations.AddField(
            model_name='giveaway',
            name='publish_to_socials',
            field=models.BooleanField(default=True),
        ),
    ]
