# Generated by Django 4.2.7 on 2023-11-01 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_giveaway_publish_to_socials'),
    ]

    operations = [
        migrations.AddField(
            model_name='giveaway',
            name='msrp',
            field=models.FloatField(null=True),
        ),
    ]
