# Generated by Django 4.2.7 on 2023-11-25 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_giveaway_msrp'),
    ]

    operations = [
        migrations.AddField(
            model_name='giveaway',
            name='show_source',
            field=models.BooleanField(default=False),
        ),
    ]
