# Generated by Django 4.2.9 on 2024-01-14 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_giveaway_show_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='giveaway',
            name='expiration_date',
            field=models.DateTimeField(
                null=True, verbose_name='expiration date'),
        ),
    ]
