# Generated by Django 4.2.10 on 2024-02-18 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_giveaway_expiration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='giveaway',
            name='steam_grid_db_image',
            field=models.TextField(blank=True),
        ),
    ]
