# Generated by Django 4.2.4 on 2023-08-14 13:12

from django.db import migrations


def forwards_func(apps, schema_editor):
    Platform = apps.get_model("backend", "Platform")
    db_alias = schema_editor.connection.alias
    Platform.objects.using(db_alias).bulk_create([
        Platform(id="legacy_games", title="Legacy Games"),
    ])


def reverse_func(apps, schema_editor):
    Platform = apps.get_model("backend", "Platform")
    db_alias = schema_editor.connection.alias
    Platform.objects.using(db_alias).filter(id="legacy_games").delete(),


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_giveaway_steam_grid_db_image'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
