# Generated by Django 4.2.4 on 2025-10-25

from django.db import migrations


def forwards_func(apps, schema_editor):
    Platform = apps.get_model("backend", "Platform")
    db_alias = schema_editor.connection.alias
    Platform.objects.using(db_alias).bulk_create([
        Platform(id="stove", title="Stove"),
    ])


def reverse_func(apps, schema_editor):
    Platform = apps.get_model("backend", "Platform")
    db_alias = schema_editor.connection.alias
    Platform.objects.using(db_alias).filter(id="stove").delete(),


class Migration(migrations.Migration):
    dependencies = [
        ('backend', '0009_platforms_legacy_games'),
    ]
    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
