name: Backend CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ENV: production
      DJANGO_SECRET_KEY: ${{ github.actor == 'dependabot[bot]' && 'SECRET_KEY_FOR_DEPENDABOT' || secrets.DJANGO_SECRET_KEY }}
      DJANGO_SUPERUSER_PASSWORD: password
      TELEGRAM_BOT_API_USERNAME: username
      TELEGRAM_BOT_API_PASSWORD: password

    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9]

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pipenv"

      - name: Install pipenv
        run: |
          python -m pip install --upgrade pipenv wheel

      - name: Install dependencies
        run: |
          pipenv install --system

      - name: Install Chromium browser
        uses: nanasess/setup-chromedriver@v2
      - run: |
          export DISPLAY=:99
          chromedriver --url-base=/wd/hub &
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # optional

      - name: Run migrations
        run: python manage.py migrate

      - name: Run Django server
        run: python manage.py runserver &

      - name: Create Django superuser
        run: python manage.py createsuperuser --noinput --username username --email email@email.com

      - name: Run tests
        run: python manage.py test
